add some type checking on pre-commit; type fixes

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,16 +1,31 @@
 #!/bin/bash
 
-echo 'Running eslint on changed code...'
+echo 'Running eslint on modified modules...'
 
-# Get all JS files which have been staged
+# Get all JS-related files which have been staged
 files=$(git diff --name-only --cached)
 js_files=$(echo "$files" | grep -E '\.(js|jsx|ts|tsx)$')
 
 # Run eslint on the filtered list of files
 if [ -n "$js_files" ]; then
-  ./node_modules/eslint/bin/eslint.js $js_files
+  ./node_modules/.bin/eslint $js_files
   if [ $? -ne 0 ]; then
     echo "ESLint found errors. Aborting commit."
+    exit 1
+  fi
+fi
+
+echo 'Done.'
+
+echo 'Running type checking on modified (and related) modules...'
+
+ts_files=$(echo "$files" | grep -E '\.(ts|tsx)$')
+
+# Run eslint on the filtered list of files
+if [ -n "$ts_files" ]; then
+  ./node_modules/.bin/tsc-files --noEmit $ts_files
+  if [ $? -ne 0 ]; then
+    echo "Tsc found type errors. Aborting commit."
     exit 1
   fi
 fi
